### ISSUE TITLE
Host code for teammates-bot

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates-ops#1]

**Comment by wkurniawan07** [comment]
@samsontmr can I trouble you to host the code for `teammates-bot` here? Subsequent development can then take place here.

**Comment by samsontmr** [comment]
@wkurniawan07 Why not just fork the oss-bot-js repo into this org?

**Comment by wkurniawan07** [comment]
@samsontmr will there be any more development there? If not I might just host all the code here for subsequent development, with your permission of course.

**Comment by samsontmr** [comment]
@wkurniawan07 not in the near future. Is there a difference between that and forking?

**Comment by wkurniawan07** [comment]
@samsontmr I can't fork a repository and make it part of this repo (not part of this org). Not that it's an only option to me, but I prefer not to create another repo unless necessary.

**Comment by samsontmr** [comment]
@wkurniawan07 oh I see what you mean. I'm not sure if the auto deployment will work as expected if you put it as a subfolder under this repo. If you're alright with that, please go ahead. I'd appreciate a credit :P

**Comment by wkurniawan07** [comment]
> I'd appreciate a credit :P

Worry not. Credit will be given where it's due.
