### ISSUE TITLE
Fix links to devGuide + Update teammates-bot to point to correct link.

### ISSUE THREAD

**Issue by kaixin-hc** [TEAMMATES/teammates-ops#26]
Corresponds to https://github.com/TEAMMATES/teammates/issues/11736
- [x] Fix links to the devGuide in the docs in this repository
- [x] ~Fix the `CONTRIBUTING_GUIDELINES` parameter in the deployment config of the teammates doc to point to the correct link.~

**Comment by wkurniawan07** [comment]
Point 2 is no longer needed as the github bot is no longer active.
