### ISSUE TITLE
StatisticsPerInstitute failing with 'out of memory' error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates-ops#7]
StatisticsPerInstitute is run at the end of every month to collect stats. This month, it is failing with this error:

>------------------ iterations count:18000 ------------------------
------------------ iterations count:19000 ------------------------
------------------ iterations count:20000 ------------------------
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

Did we do something to the backend during last month which could have caused this error?

**Comment by wkurniawan07** [comment]
This could very well be a scalability issue. Previously, how many iterations are there before the script stops?

**Comment by damithc** [comment]
Previous round was around 400k iterations. This script had a similar scalability issue about 1.5 years ago and was fixed by a summer intern.

**Comment by damithc** [comment]
BTW, not urgent. It's fine to skip stats for one month. Most stats are provided by GAE anyway.

**Comment by xpdavid** [comment]
Will increase of Java heap work? If it is, it is a scalability issue and we need to devise a new script to collect the stats instead (The current loading of all instructors/students/accounts is already a red alert to me.).

**Comment by damithc** [comment]
Tried with 1GB, didn't help. Will try with a higher heap later. It looks like the script is doing a lot more than 20K iterations as the script gets stuck at 20K for a long time before it crashes.  It's quite possible that in this month we simply went past the limit the script is able to handle.
